[settings]
; PJSIP
ps_endpoints => odbc,asterisk
ps_auths => odbc,asterisk
ps_aors => odbc,asterisk
ps_contacts => odbc,asterisk
ps_registrations => odbc,asterisk
ps_identifies => odbc,asterisk
ps_domain_aliases => odbc,asterisk

; Dialplan
extensions => odbc,asterisk

; Queues
queues => odbc,asterisk
queue_members => odbc,asterisk

; Reporting
queue_log => odbc,asterisk
cdr => odbc,asterisk
cel => odbc,asterisk

; Voicemail
voicemail => odbc,asterisk
