[modules]
autoload=yes

; Core ODBC
preload => res_odbc.so
preload => res_config_odbc.so

; Realtime Backends
load => res_pjsip_exten_state.so
load => res_pjsip_config_helper.so

; Dialplan and Features
load => pbx_realtime.so
load => app_queue.so
load => app_voicemail.so

; Reporting Modules
load => cdr_adaptive_odbc.so
; SIP Modules to avoid crashes on ARM64 if specific features are unused
noload => res_pjsip_outbound_registration.so
noload => res_pjsip_outbound_publish.so
