[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
; NAT Settings - Replace with your public IP if necessary
external_media_address=192.168.1.100
external_signaling_address=192.168.1.100
allow_reload=yes

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
external_media_address=192.168.1.100
external_signaling_address=192.168.1.100
allow_reload=yes
