[asterisk]
dbstrategy => optimize

; PJSIP
ps_endpoints => asterisk,ps_endpoints
ps_auths => asterisk,ps_auths
ps_aors => asterisk,ps_aors
ps_contacts => asterisk,ps_contacts
ps_registrations => asterisk,ps_registrations
ps_identifies => asterisk,ps_identifies
ps_domain_aliases => asterisk,ps_domain_aliases

; Dialplan
extensions => asterisk,extensions

; Queues
queues => asterisk,queues
queue_members => asterisk,queue_members

; Voicemail
voicemail => asterisk,voicemail
